/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedPricesRouteImport } from './routes/_authenticated/prices'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedSchemesRouteImport } from './routes/_authenticated/schemes'
import { Route as AuthenticatedYieldRouteImport } from './routes/_authenticated/yield'
import { Route as AuthenticatedScanScanIdRouteImport } from './routes/_authenticated/scan.$scanId'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPricesRoute = AuthenticatedPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchemesRoute = AuthenticatedSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedYieldRoute = AuthenticatedYieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanScanIdRoute = AuthenticatedScanScanIdRouteImport.update({
  id: '/$scanId',
  path: '/$scanId',
  getParentRoute: () => AuthenticatedScanRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/google/callback',
  path: '/google/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/scan': typeof AuthenticatedScanRouteWithChildren
  '/schemes': typeof AuthenticatedSchemesRoute
  '/yield': typeof AuthenticatedYieldRoute
  '/scan/$scanId': typeof AuthenticatedScanScanIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/prices': typeof AuthenticatedPricesRoute
  '/scan': typeof AuthenticatedScanRouteWithChildren
  '/schemes': typeof AuthenticatedSchemesRoute
  '/yield': typeof AuthenticatedYieldRoute
  '/scan/$scanId': typeof AuthenticatedScanScanIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/prices': typeof AuthenticatedPricesRoute
  '/_authenticated/scan': typeof AuthenticatedScanRouteWithChildren
  '/_authenticated/schemes': typeof AuthenticatedSchemesRoute
  '/_authenticated/yield': typeof AuthenticatedYieldRoute
  '/_authenticated/scan/$scanId': typeof AuthenticatedScanScanIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/calendar'
    | '/chat'
    | '/dashboard'
    | '/marketplace'
    | '/prices'
    | '/scan'
    | '/schemes'
    | '/yield'
    | '/scan/$scanId'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/calendar'
    | '/chat'
    | '/dashboard'
    | '/marketplace'
    | '/prices'
    | '/scan'
    | '/schemes'
    | '/yield'
    | '/scan/$scanId'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/calendar'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/marketplace'
    | '/_authenticated/prices'
    | '/_authenticated/scan'
    | '/_authenticated/schemes'
    | '/_authenticated/yield'
    | '/_authenticated/scan/$scanId'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prices': {
      id: '/_authenticated/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof AuthenticatedPricesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schemes': {
      id: '/_authenticated/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AuthenticatedSchemesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yield': {
      id: '/_authenticated/yield'
      path: '/yield'
      fullPath: '/yield'
      preLoaderRoute: typeof AuthenticatedYieldRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan/$scanId': {
      id: '/_authenticated/scan/$scanId'
      path: '/$scanId'
      fullPath: '/scan/$scanId'
      preLoaderRoute: typeof AuthenticatedScanScanIdRouteImport
      parentRoute: typeof AuthenticatedScanRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthenticatedScanRouteChildren {
  AuthenticatedScanScanIdRoute: typeof AuthenticatedScanScanIdRoute
}

const AuthenticatedScanRouteChildren: AuthenticatedScanRouteChildren = {
  AuthenticatedScanScanIdRoute: AuthenticatedScanScanIdRoute,
}

const AuthenticatedScanRouteWithChildren =
  AuthenticatedScanRoute._addFileChildren(AuthenticatedScanRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedPricesRoute: typeof AuthenticatedPricesRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRouteWithChildren
  AuthenticatedSchemesRoute: typeof AuthenticatedSchemesRoute
  AuthenticatedYieldRoute: typeof AuthenticatedYieldRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedPricesRoute: AuthenticatedPricesRoute,
  AuthenticatedScanRoute: AuthenticatedScanRouteWithChildren,
  AuthenticatedSchemesRoute: AuthenticatedSchemesRoute,
  AuthenticatedYieldRoute: AuthenticatedYieldRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
